- name: facts
  hosts: all
  gather_facts: no
  tasks:
    - setup:
        gather_subset:
          - '!all'
          - processor
          - user_id

- name: run lavalauncher role
  gather_facts: no
  hosts: laptop
  vars_files:
    - vars/nord.yml
  roles: 
    - lavalauncher

- name: run roles
  gather_facts: no
  hosts: all
  vars_files:
    - vars/nord.yml
  roles:
    - fish
    - foot
    - pipewire
    - mako
    - sway
    - mpv
    - iptables
    - logiops
    - runsvdir-user
    - syncthing
