- name: install foot
  become: yes
  community.general.xbps:
    name: 
      - foot
      - nerd-fonts
      - font-tamzen
    state: present

- name: template foot config
  block:
    - file:
        path: "/home/{{ ansible_facts.user_id }}/.config/foot"
        state: directory
    - template:
        dest: "/home/{{ ansible_facts.user_id }}/.config/foot/foot.ini"
        src: foot.ini.j2
        mode: 0644
