- name: install syncthing
  become: yes
  community.general.xbps:
    name: syncthing
    state: present

- name: check if per user services are enabled
  block:
    - stat: 
        path: "/home/{{ ansible_facts.user_id }}/.config/runit"
      register: runitConfig
    - stat:
        path: "/etc/sv/runsvdir-{{ ansible_facts.user_id }}"
      register: runsvdirUser

- name: copy service config
  block:
    - file:
        path: "/home/{{ ansible_facts.user_id }}/.config/runit/syncthing"
        state: directory
    - copy:
        dest: "/home/{{ ansible_facts.user_id }}/.config/runit/syncthing/run"
        src: syncthing-service-run
        mode: 0755
  when: runsvdirUser.stat.exists and runitConfig.stat.exists

- name: check if iptables rules are present
  stat:
    path: "/etc/iptables/iptables.rules"
  register: iptablesRules

- name: add syncthing port to firewall
  become: yes
  blockinfile:
    path: "/etc/iptables/iptables.rules"
    insertafter: "lo"
    block: |
      -A INPUT -p tcp --dport 22000 -j ACCEPT
      -A INPUT -p udp --dport 22000 -j ACCEPT
      -A INPUT -p udp --dport 21027 -j ACCEPT
